version: '3.7'

services:

  web:
    build: ./project
    image: web
    container_name: web
    ports:
      - 8000:8000
    volumes:
      - ./project:/srv
    command: sh /srv/app/start.sh
    environment:
      - DEBUG=True
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  celery:
    image: web
    volumes:
      - ./project:/srv
      - ./project/logs:/srv/logs
    command: >
      sh -c 'truncate -s 0 logs/celery.log
      && celery -A app.tasks worker --loglevel=info  --logfile=logs/celery.log'
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:alpine

  monitor:
    image: web
    ports:
      - 5555:5555
    volumes:
      - ./project:/srv
    command:  flower -A app.tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - web
      - redis
